const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Scholarship = require('../models/Scholarship');
dotenv.config();

const scholarshipsData = [
  {
    "name": "Post Matric Scholarship for SC Students",
    "type": "Central",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG","Diploma"],
    "eligible_categories": ["SC"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["All"],
    "description": "Financial assistance to SC students studying at post matriculation or post-secondary stage.",
    "benefits": "Tuition fee reimbursement and maintenance allowance",
    "documents_required": ["Income Certificate", "Caste Certificate", "Aadhar Card"],
    "deadline": new Date("2026-10-31"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "Post Matric Scholarship for ST Students",
    "type": "Central",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG"],
    "eligible_categories": ["ST"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["All"],
    "description": "Financial assistance to ST students studying at post matriculation or post-secondary stage.",
    "benefits": "Maintenance allowance and tuition support",
    "documents_required": ["Income Certificate", "Caste Certificate", "Aadhar Card"],
    "deadline": new Date("2026-10-31"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "National Means Cum Merit Scholarship",
    "type": "Central",
    "scholarship_level": "School",
    "eligible_classes": ["8th","9th","10th","11th","12th"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 350000,
    "states": ["All"],
    "description": "Award scholarships to meritorious students of economically weaker sections to arrest their drop out at class VIII.",
    "benefits": "₹12,000 per year",
    "documents_required": ["Income Certificate", "Mark Sheet", "Aadhar Card"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "AICTE Pragati Scholarship",
    "type": "Central",
    "scholarship_level": "UG",
    "eligible_classes": ["Engineering","Diploma"],
    "eligible_categories": ["All"],
    "eligible_gender": "Female",
    "income_limit": 800000,
    "states": ["All"],
    "description": "Scheme being implemented by AICTE aimed at providing assistance for Advancement of Girls pursuing Technical Education.",
    "benefits": "₹50,000 per year",
    "documents_required": ["Income Certificate", "Admission Letter", "Aadhar Card"],
    "deadline": new Date("2026-10-31"),
    "apply_link": "https://aicte-india.org"
  },
  {
    "name": "AICTE Saksham Scholarship",
    "type": "Central",
    "scholarship_level": "UG",
    "eligible_classes": ["Engineering","Diploma"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 800000,
    "states": ["All"],
    "description": "Scheme implemented by AICTE aimed at providing encouragement and support to specially-abled children to pursue Technical Education.",
    "benefits": "₹50,000 per year for disabled students",
    "documents_required": ["Disability Certificate", "Income Certificate", "Admission Letter"],
    "deadline": new Date("2026-10-31"),
    "apply_link": "https://aicte-india.org"
  },
  {
    "name": "INSPIRE Scholarship",
    "type": "Central",
    "scholarship_level": "UG",
    "eligible_classes": ["BSc","MSc"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 800000,
    "states": ["All"],
    "description": "Innovation in Science Pursuit for Inspired Research (INSPIRE) for students studying Natural/Basic sciences.",
    "benefits": "₹80,000 per year",
    "documents_required": ["12th Board Endorsement", "Admission Proof"],
    "deadline": new Date("2026-09-15"),
    "apply_link": "https://online-inspire.gov.in"
  },
  {
    "name": "Prime Minister Scholarship Scheme",
    "type": "Central",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["Defense"],
    "eligible_gender": "All",
    "income_limit": 800000,
    "states": ["All"],
    "description": "To encourage higher technical and professional education for the dependent wards of Ex-Servicemen / Ex-Coast Guard personnel.",
    "benefits": "₹25,000 per year",
    "documents_required": ["Discharge Book", "PPO", "Bonafide Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://ksb.gov.in"
  },
  {
    "name": "Top Class Education Scholarship for SC",
    "type": "Central",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["SC"],
    "eligible_gender": "All",
    "income_limit": 800000,
    "states": ["All"],
    "description": "Aims at recognizing and promoting quality education amongst students belonging to SC by providing full financial support.",
    "benefits": "Full tuition + stipend",
    "documents_required": ["Caste Certificate", "Income Certificate", "Admission Proof"],
    "deadline": new Date("2026-10-31"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "Top Class Education Scholarship for ST",
    "type": "Central",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["ST"],
    "eligible_gender": "All",
    "income_limit": 600000,
    "states": ["All"],
    "description": "Aims at recognizing and promoting quality education amongst students belonging to ST by providing full financial support.",
    "benefits": "Full tuition fee",
    "documents_required": ["Caste Certificate", "Income Certificate", "Admission Proof"],
    "deadline": new Date("2026-10-31"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "Merit Cum Means Scholarship for Minorities",
    "type": "Central",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG"],
    "eligible_categories": ["Minority"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["All"],
    "description": "Provides financial assistance to the poor and meritorious students belonging to minority communities.",
    "benefits": "Course fee support",
    "documents_required": ["Income Certificate", "Minority Certificate", "Mark Sheet"],
    "deadline": new Date("2026-10-15"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "MP Medhavi Vidyarthi Yojana",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 600000,
    "states": ["Madhya Pradesh"],
    "description": "Financial assistance program for deserving students of MP.",
    "benefits": "Full tuition fee",
    "documents_required": ["Domicile Certificate", "Income Certificate", "Aadhar Card"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://scholarshipportal.mp.nic.in"
  },
  {
    "name": "MP Gaon Ki Beti Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "Female",
    "income_limit": 600000,
    "states": ["Madhya Pradesh"],
    "description": "Encourages higher education among rural girls in Madhya Pradesh.",
    "benefits": "₹5000 per year",
    "documents_required": ["Domicile Certificate", "Income Certificate", "Aadhar Card"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://hescholarship.mp.gov.in/Index.aspx"
  },
  {
    "name": "UP Post Matric Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG"],
    "eligible_categories": ["SC","ST","OBC","General"],
    "eligible_gender": "All",
    "income_limit": 200000,
    "states": ["Uttar Pradesh"],
    "description": "State sponsored post matric scholarship for UP domicile students.",
    "benefits": "Tuition fee reimbursement",
    "documents_required": ["Domicile Certificate", "Income Certificate", "Aadhar Card"],
    "deadline": new Date("2026-09-20"),
    "apply_link": "https://scholarship.up.gov.in"
  },
  {
    "name": "UP Pre Matric Scholarship",
    "type": "State",
    "scholarship_level": "School",
    "eligible_classes": ["9th","10th"],
    "eligible_categories": ["SC","ST","OBC","Minority"],
    "eligible_gender": "All",
    "income_limit": 100000,
    "states": ["Uttar Pradesh"],
    "description": "State sponsored pre matric scholarship for UP domicile students.",
    "benefits": "Monthly stipend",
    "documents_required": ["Domicile Certificate", "Income Certificate", "Aadhar Card"],
    "deadline": new Date("2026-09-10"),
    "apply_link": "https://scholarship.up.gov.in"
  },
  {
    "name": "Maharashtra Rajarshi Shahu Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["OBC"],
    "eligible_gender": "All",
    "income_limit": 800000,
    "states": ["Maharashtra"],
    "description": "Scholarship for economically backward class students studying in Maharashtra.",
    "benefits": "₹10,000 yearly",
    "documents_required": ["Domicile Certificate", "Income Certificate", "Aadhar Card"],
    "deadline": new Date("2026-09-25"),
    "apply_link": "https://mahadbt.maharashtra.gov.in"
  },
  {
    "name": "Jharkhand E-Kalyan Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG"],
    "eligible_categories": ["SC","ST"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["Jharkhand"],
    "description": "State sponsored post matric scholarship for Jharkhand domicile students.",
    "benefits": "Maintenance allowance",
    "documents_required": ["Domicile Certificate", "Income Certificate", "Aadhar Card"],
    "deadline": new Date("2026-09-20"),
    "apply_link": "https://ekalyan.cgg.gov.in"
  },
  {
    "name": "Karnataka Vidyasiri Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["OBC","SC","ST"],
    "eligible_gender": "All",
    "income_limit": 200000,
    "states": ["Karnataka"],
    "description": "Scholarship for students studying in post-matric courses and staying in hostels.",
    "benefits": "Hostel fee support",
    "documents_required": ["Domicile Certificate", "Income Certificate", "Aadhar Card"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://ssp.karnataka.gov.in"
  },
  {
    "name": "Tamil Nadu First Graduate Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 500000,
    "states": ["Tamil Nadu"],
    "description": "Concession for students who are the first graduates in their family.",
    "benefits": "Tuition fee support",
    "documents_required": ["Domicile Certificate", "Income Certificate", "First Graduate Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://tnscholarship.gov.in"
  },
  {
    "name": "Digital Gujarat Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG"],
    "eligible_categories": ["SC","ST","OBC"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["Gujarat"],
    "description": "Scholarship for backward classes students studying in Gujarat.",
    "benefits": "Education allowance",
    "documents_required": ["Domicile Certificate", "Income Certificate", "Aadhar Card"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://digitalgujarat.gov.in"
  },
  {
    "name": "Swami Vivekananda Merit Cum Means Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["West Bengal"],
    "description": "Assists the meritorious students having economically backward families in West Bengal.",
    "benefits": "₹12,000 yearly",
    "documents_required": ["Domicile Certificate", "Income Certificate", "Aadhar Card"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://svmcm.wb.gov.in"
  },
  {
    "name": "Begum Hazrat Mahal National Scholarship",
    "type": "Central",
    "scholarship_level": "School",
    "eligible_classes": ["9th","10th","11th","12th"],
    "eligible_categories": ["Minority"],
    "eligible_gender": "Female",
    "income_limit": 200000,
    "states": ["All"],
    "description": "Financial assistance for meritorious minority girl students.",
    "benefits": "₹5,000–₹6,000 yearly",
    "documents_required": ["Income Certificate", "Minority Certificate", "Aadhar Card"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "Pre Matric Scholarship for Minorities",
    "type": "Central",
    "scholarship_level": "School",
    "eligible_classes": ["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th"],
    "eligible_categories": ["Minority"],
    "eligible_gender": "All",
    "income_limit": 100000,
    "states": ["All"],
    "description": "Financial assistance for minority students studying at pre matriculation level.",
    "benefits": "Maintenance allowance",
    "documents_required": ["Income Certificate", "Minority Certificate"],
    "deadline": new Date("2026-09-15"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "Post Matric Scholarship for Minorities",
    "type": "Central",
    "scholarship_level": "UG",
    "eligible_classes": ["11th","12th","UG","PG"],
    "eligible_categories": ["Minority"],
    "eligible_gender": "All",
    "income_limit": 200000,
    "states": ["All"],
    "description": "Financial assistance for minority students studying at post matriculation level.",
    "benefits": "Course fee + stipend",
    "documents_required": ["Income Certificate", "Minority Certificate", "Aadhar Card"],
    "deadline": new Date("2026-10-15"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "ISHAN UDAY Scholarship",
    "type": "Central",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 450000,
    "states": ["Assam","Arunachal Pradesh","Manipur","Meghalaya","Mizoram","Nagaland","Tripura","Sikkim"],
    "description": "Special scheme by UGC for North Eastern Region students.",
    "benefits": "₹5,400 per month",
    "documents_required": ["Domicile Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "National Fellowship for SC Students",
    "type": "Central",
    "scholarship_level": "Research",
    "eligible_classes": ["PG"],
    "eligible_categories": ["SC"],
    "eligible_gender": "All",
    "income_limit": 800000,
    "states": ["All"],
    "description": "Fellowship scheme for SC students pursuing higher studies like M.Phil or Ph.D.",
    "benefits": "Research stipend",
    "documents_required": ["Caste Certificate", "Admission Proof"],
    "deadline": new Date("2026-10-31"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "National Fellowship for ST Students",
    "type": "Central",
    "scholarship_level": "Research",
    "eligible_classes": ["PG"],
    "eligible_categories": ["ST"],
    "eligible_gender": "All",
    "income_limit": 800000,
    "states": ["All"],
    "description": "Fellowship scheme for ST students pursuing higher studies like M.Phil or Ph.D.",
    "benefits": "Research fellowship",
    "documents_required": ["Caste Certificate", "Admission Proof"],
    "deadline": new Date("2026-10-31"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "National Overseas Scholarship for SC Students",
    "type": "Central",
    "scholarship_level": "PG",
    "eligible_classes": ["PG"],
    "eligible_categories": ["SC"],
    "eligible_gender": "All",
    "income_limit": 800000,
    "states": ["All"],
    "description": "Financial assistance to SC students for pursuing Master's level courses uniquely abroad.",
    "benefits": "Overseas tuition support",
    "documents_required": ["Caste Certificate", "Income Certificate", "Passport"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://scholarships.gov.in"
  },
  {
    "name": "NTSE Scholarship",
    "type": "Central",
    "scholarship_level": "School",
    "eligible_classes": ["10th","11th","12th"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 800000,
    "states": ["All"],
    "description": "National Talent Search Examination scheme for meritorious students.",
    "benefits": "Monthly stipend",
    "documents_required": ["Mark Sheet", "Aadhar Card"],
    "deadline": new Date("2026-08-30"),
    "apply_link": "https://ncert.nic.in"
  },
  {
    "name": "MP Vikramaditya Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["General"],
    "eligible_gender": "All",
    "income_limit": 120000,
    "states": ["Madhya Pradesh"],
    "description": "Financial assistance under Vikramaditya scheme for MP domicile students.",
    "benefits": "₹2,500 yearly",
    "documents_required": ["Domicile Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://scholarshipportal.mp.nic.in"
  },
  {
    "name": "MP Pratibha Kiran Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "Female",
    "income_limit": 600000,
    "states": ["Madhya Pradesh"],
    "description": "Scholarship encouraging female education for MP domicile candidates.",
    "benefits": "₹5,000 yearly",
    "documents_required": ["Domicile Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://scholarshipportal.mp.nic.in"
  },
  {
    "name": "UP Dashmottar Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG"],
    "eligible_categories": ["SC","ST","OBC"],
    "eligible_gender": "All",
    "income_limit": 200000,
    "states": ["Uttar Pradesh"],
    "description": "UP state post matric scholarship scheme.",
    "benefits": "Maintenance allowance",
    "documents_required": ["Domicile Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-20"),
    "apply_link": "https://scholarship.up.gov.in"
  },
  {
    "name": "UP Minority Scholarship",
    "type": "State",
    "scholarship_level": "School",
    "eligible_classes": ["9th","10th","11th","12th"],
    "eligible_categories": ["Minority"],
    "eligible_gender": "All",
    "income_limit": 200000,
    "states": ["Uttar Pradesh"],
    "description": "UP state scholarship scheme for minority communities.",
    "benefits": "Course support",
    "documents_required": ["Minority Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-20"),
    "apply_link": "https://scholarship.up.gov.in"
  },
  {
    "name": "UP Merit Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["Uttar Pradesh"],
    "description": "Merit based scholarship scheme for UP students.",
    "benefits": "₹10,000 yearly",
    "documents_required": ["Mark Sheet", "Domicile Certificate"],
    "deadline": new Date("2026-09-25"),
    "apply_link": "https://scholarship.up.gov.in"
  },
  {
    "name": "Maharashtra EBC Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["General"],
    "eligible_gender": "All",
    "income_limit": 800000,
    "states": ["Maharashtra"],
    "description": "Economically backward class scholarship for general category students in Maharashtra.",
    "benefits": "50% tuition fee support",
    "documents_required": ["Income Certificate", "Domicile Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://mahadbt.maharashtra.gov.in"
  },
  {
    "name": "Maharashtra Minority Scholarship",
    "type": "State",
    "scholarship_level": "School",
    "eligible_classes": ["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th"],
    "eligible_categories": ["Minority"],
    "eligible_gender": "All",
    "income_limit": 200000,
    "states": ["Maharashtra"],
    "description": "Maharashtra state pre matric scholarship for minority students.",
    "benefits": "Educational allowance",
    "documents_required": ["Minority Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://mahadbt.maharashtra.gov.in"
  },
  {
    "name": "Jharkhand Pre Matric Scholarship",
    "type": "State",
    "scholarship_level": "School",
    "eligible_classes": ["9th","10th"],
    "eligible_categories": ["SC","ST"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["Jharkhand"],
    "description": "Jharkhand pre matric aid for specific categories.",
    "benefits": "Monthly stipend",
    "documents_required": ["Caste Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-20"),
    "apply_link": "https://ekalyan.cgg.gov.in"
  },
  {
    "name": "Jharkhand Post Matric Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG"],
    "eligible_categories": ["SC","ST"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["Jharkhand"],
    "description": "Jharkhand post matric scheme for students.",
    "benefits": "Course fee reimbursement",
    "documents_required": ["Caste Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-20"),
    "apply_link": "https://ekalyan.cgg.gov.in"
  },
  {
    "name": "Karnataka Fee Reimbursement Scheme",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["SC","ST","OBC"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["Karnataka"],
    "description": "State scheme providing direct fee reimbursement to qualifying candidates.",
    "benefits": "Tuition reimbursement",
    "documents_required": ["Domicile Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://ssp.karnataka.gov.in"
  },
  {
    "name": "Karnataka Minority Scholarship",
    "type": "State",
    "scholarship_level": "School",
    "eligible_classes": ["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th"],
    "eligible_categories": ["Minority"],
    "eligible_gender": "All",
    "income_limit": 200000,
    "states": ["Karnataka"],
    "description": "Scholarship for minority students in Karnataka pre-matric.",
    "benefits": "Education allowance",
    "documents_required": ["Minority Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://ssp.karnataka.gov.in"
  },
  {
    "name": "Tamil Nadu BC/MBC Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG"],
    "eligible_categories": ["OBC"],
    "eligible_gender": "All",
    "income_limit": 200000,
    "states": ["Tamil Nadu"],
    "description": "Scholarship tailored to Backward Class and Most Backward Class candidates.",
    "benefits": "Course fee assistance",
    "documents_required": ["Caste Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://tnscholarship.gov.in"
  },
  {
    "name": "Tamil Nadu Post Matric Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG"],
    "eligible_categories": ["SC","ST"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["Tamil Nadu"],
    "description": "Post matric scheme intended to support Tamil Nadu ST/SC students.",
    "benefits": "Maintenance allowance",
    "documents_required": ["Caste Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://tnscholarship.gov.in"
  },
  {
    "name": "Gujarat Mukhyamantri Yuva Swavalamban Yojana",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 600000,
    "states": ["Gujarat"],
    "description": "Scheme designed to incentivize self sustainable education among youths.",
    "benefits": "Tuition fee support",
    "documents_required": ["Domicile Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://mysy.guj.nic.in"
  },
  {
    "name": "Rajasthan Post Matric Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG","PG"],
    "eligible_categories": ["SC","ST","OBC"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["Rajasthan"],
    "description": "Rajasthan scholarship for under-represented categories in higher education.",
    "benefits": "Course fee reimbursement",
    "documents_required": ["Domicile Certificate", "Caste Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-25"),
    "apply_link": "https://sje.rajasthan.gov.in"
  },
  {
    "name": "Rajasthan Chief Minister Higher Education Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["Rajasthan"],
    "description": "Scholarship explicitly to facilitate continued higher education.",
    "benefits": "₹5,000 yearly",
    "documents_required": ["Domicile Certificate", "Income Certificate"],
    "deadline": new Date("2026-09-25"),
    "apply_link": "https://hte.rajasthan.gov.in"
  },
  {
    "name": "West Bengal Kanyashree Scholarship",
    "type": "State",
    "scholarship_level": "School",
    "eligible_classes": ["11th","12th"],
    "eligible_categories": ["All"],
    "eligible_gender": "Female",
    "income_limit": 200000,
    "states": ["West Bengal"],
    "description": "Major initiative supporting the continued education of female students.",
    "benefits": "₹25,000 grant",
    "documents_required": ["Domicile Certificate", "Birth Certificate"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://kanyashree.gov.in"
  },
  {
    "name": "Bihar Chief Minister Kanya Utthan Yojana",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "Female",
    "income_limit": 300000,
    "states": ["Bihar"],
    "description": "A focused initiative geared towards encouraging secondary education among young women.",
    "benefits": "₹25,000 incentive",
    "documents_required": ["Domicile Certificate", "Aadhar Card"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://medhasoft.bih.nic.in"
  },
  {
    "name": "Assam Pragyan Bharati Scholarship",
    "type": "State",
    "scholarship_level": "School",
    "eligible_classes": ["11th","12th"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 200000,
    "states": ["Assam"],
    "description": "Educational aid directly offering free learning material assistance.",
    "benefits": "Free textbooks and support",
    "documents_required": ["Domicile Certificate"],
    "deadline": new Date("2026-09-20"),
    "apply_link": "https://directorateofhighereducation.assam.gov.in"
  },
  {
    "name": "Odisha Biju Yuva Sashaktikaran Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["Odisha"],
    "description": "Technical and material assistance aiding modern students of Odisha.",
    "benefits": "Laptop and stipend",
    "documents_required": ["Domicile Certificate", "Mark Sheet"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://scholarship.odisha.gov.in"
  },
  {
    "name": "Kerala Higher Education Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 300000,
    "states": ["Kerala"],
    "description": "Financial aid targeted at supporting higher educational aspirations in Kerala.",
    "benefits": "₹12,000 yearly",
    "documents_required": ["Domicile Certificate", "Bank Passbook"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://dcescholarship.kerala.gov.in"
  },
  {
    "name": "Delhi Merit Scholarship",
    "type": "State",
    "scholarship_level": "UG",
    "eligible_classes": ["UG"],
    "eligible_categories": ["All"],
    "eligible_gender": "All",
    "income_limit": 250000,
    "states": ["Delhi"],
    "description": "Regional Delhi incentive provided solely based on academic merit scores.",
    "benefits": "Merit based stipend",
    "documents_required": ["Domicile Certificate", "Mark Sheet"],
    "deadline": new Date("2026-09-30"),
    "apply_link": "https://edudel.nic.in"
  }
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    await Scholarship.deleteMany({});
    console.log("Deleted old scholarships");

    await Scholarship.insertMany(scholarshipsData);
    console.log(`Seeded ${scholarshipsData.length} scholarships successfully`);

    process.exit(0);
  } catch (error) {
    console.error("Error seeding data:", error);
    process.exit(1);
  }
};

seedDB();
